networks:
  t3_proxy:
    name: t3_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.90.0/24
  socket_proxy:
    name: socket_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.91.0/24
  db:
    name: db
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.92.0/24
  downloaders:
    name: downloaders
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.93.0/24
  ops:
    name: ops
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.94.0/24

secrets:
  postgres_default_password:
    file: $DOCKERDIR/secrets/postgres_default_password
  authentik_postgres_user:
    file: $DOCKERDIR/secrets/authentik_postgres_user
  authentik_postgres_password:
    file: $DOCKERDIR/secrets/authentik_postgres_password
  authentik_secret_key:
    file: $DOCKERDIR/secrets/authentik_secret_key

include:
  # CORE
  - compose/socket-proxy.yml
  - compose/traefik.yml
  - compose/authentik.yml
  # MEDIA
  - compose/jellyfin.yml
  # APPS
  - compose/portainer.yml
  # - compose/homepage.yml
  # DOWNLOADERS
  - compose/sabnzbd.yml
  # PVRS
  - compose/radarr.yml
  - compose/sonarr.yml
  # MONITORING
  - compose/whoami.yml
  - compose/grafana.yml
  - compose/prometheus.yml
  - compose/radarr-exporter.yml
  - compose/sabnzbd-exporter.yml
  - compose/sonarr-exporter.yml
  - compose/dozzle.yml
  # MAINTENANCE
  - compose/docker-gc.yml

