services:
  jellyseerr:
    image: ghcr.io/fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    environment:
      - LOG_LEVEL=info
      - TZ=$TZ
    volumes:
      - $DOCKERDIR/appdata/jellyseerr:/app/config
    labels:
      - traefik.enable=true
      - traefik.http.routers.jellyseerr-rtr.entrypoints=websecure
      - traefik.http.routers.jellyseerr-rtr.rule=Host(`jellyseerr.$DOMAINNAME`)
      - traefik.http.routers.jellyseerr-rtr.service=jellyseerr-svc
      - traefik.http.routers.jellyseerr-rtr.middlewares=chain-no-auth@file
      - traefik.http.services.jellyseerr-svc.loadbalancer.server.port=5055
