# Portainer - WebUI for Containers
services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      - t3_proxy
      - socket_proxy
    command: -H tcp://socket-proxy:2375
    volumes:
      - $DOCKERDIR/appdata/portainer/data:/data
    environment:
      - TZ=$TZ
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer-rtr.entrypoints=websecure
      - traefik.http.routers.portainer-rtr.rule=Host(`portainer.$DOMAINNAME`)
      - traefik.http.routers.portainer-rtr.service=portainer-svc
      # Portainer uses its own auth
      # - traefik.http.routers.portainer-rtr.middlewares=chain-authentik@file
      - traefik.http.services.portainer-svc.loadbalancer.server.port=9000
      - homepage.group=Management
      - homepage.name=Portainer
      - homepage.icon=portainer.png
      - homepage.href=http://portainer.$DOMAINNAME/
      - homepage.description=Container Management

