services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    security_opt:
      - no-new-privileges:true
    restart: "unless-stopped"
    networks:
      - ops
    # ports:
    #   - "9090:9090"
    volumes:
      - $DOCKERDIR/appdata/prometheus:/etc/prometheus
