# Prometheus metrics exporter for radarr
services:
  radarr-exporter:
    container_name: radarr-exporter
    image: ghcr.io/onedr0p/exportarr:latest
    security_opt:
      - no-new-privileges:true
    restart: "unless-stopped"
    networks:
      - ops
    # ports:
    #   - "9712:9712"
    environment:
      PORT: 9708
      URL: "http://radarr:7878"
      APIKEY: $RADARR_API_KEY
      ENABLE_ADDITIONAL_METRICS: TRUE
    command: ["radarr"]