# Redis - Key-value Store
services:
  redis:
    container_name: redis
    image: docker.io/library/redis:alpine
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    command: --save 60 1 --loglevel warning
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    networks:
      - db
    # ports:
    #   - $REDIS_PORT:6379
    volumes:
      - $DOCKERDIR/appdata/redis:/data

