# SABnzbd - Binary newsgrabber (NZB downloader)
services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      - t3_proxy
      - downloaders
      - ops
    volumes:
      - $DOCKERDIR/appdata/sabnzbd:/config
      - $DOWNLOADSDIR:/data/downloads
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      UMASK_SET: 002
    labels:
      - traefik.enable=true
      - traefik.http.routers.sabnzbd-rtr.entrypoints=websecure
      - traefik.http.routers.sabnzbd-rtr.rule=Host(`sabnzbd.$DOMAINNAME`)
      - traefik.http.routers.sabnzbd-rtr.service=sabnzbd-svc
      - traefik.http.routers.sabnzbd-rtr.middlewares=chain-authentik@file
      - traefik.http.services.sabnzbd-svc.loadbalancer.server.port=8080

  sabnzbd-exporter:
    container_name: sabnzbd-exporter
    image: ghcr.io/onedr0p/exportarr:latest
    security_opt:
      - no-new-privileges:true
    restart: "unless-stopped"
    networks:
      - ops
    # ports:
    #   - "9710:9710"
    environment:
      PORT: 9710
      URL: "http://sabnzbd:8080"
      APIKEY: $SABNZBD_API_KEY
      ENABLE_ADDITIONAL_METRICS: TRUE
    command: ["sabnzbd"]
