# Sonarr - TV Shows Management
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      - t3_proxy
      - downloaders
      - ops
    # ports:
    #   - "8989:8989"
    volumes:
      - $DOCKERDIR/appdata/sonarr:/config
      - $SHAREDDIR/media/Shows:/data/shows
      - $DOWNLOADSDIR:/data/downloads
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    labels:
      - traefik.enable=true
      - traefik.http.routers.sonarr-rtr.entrypoints=websecure
      - traefik.http.routers.sonarr-rtr.rule=Host(`sonarr.$DOMAINNAME`)
      - traefik.http.routers.sonarr-rtr.service=sonarr-svc
      - traefik.http.routers.sonarr-rtr.middlewares=chain-authentik@file
      - traefik.http.services.sonarr-svc.loadbalancer.server.port=8989
