# Prometheus metrics exporter for sonarr
services:
  sonarr-exporter:
    image: ghcr.io/onedr0p/exportarr:latest
    container_name: sonarr-exporter
    security_opt:
      - no-new-privileges:true
    restart: "unless-stopped"
    networks:
      - ops
    environment:
      PORT: 9707
      URL: "http://sonarr:8989"
      APIKEY: $SONARR_API_KEY
      ENABLE_ADDITIONAL_METRICS: TRUE
    command: ["sonarr"]
