# Traefik 3 Reverse Proxy
services:
  traefik:
    image: traefik:latest
    container_name: traefik
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      t3_proxy:
        ipv4_address: 192.168.90.254
      socket_proxy:
    ports:
      - 80:80
      - 443:443
    command:
      - --global.checkNewVersion=true
      - --global.sendAnonymousUsage=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls=true
      # - --entrypoints.websecure.asDefault=true
      - --entrypoints.websecure.forwardedHeaders.trustedIPs=$CLOUDFLARE_IPS,$LOCAL_IPS
      - --serversTransport.insecureSkipVerify=true
      # - --entrypoints.web.http.redirections.entrypoint.to=websecure
      # - --entrypoints.web.http.redirections.entrypoint.scheme=https
      # - --entrypoints.web.http.redirections.entrypoint.permanent=true
      - --api=true
      - --api.dashboard=true
      # - --api.insecure=true
      - --log=true
      - --log.filePath=/logs/traefik.log
      - --log.level=INFO
      - --accessLog=true
      - --accessLog.filePath=/logs/access.log
      - --accessLog.bufferingSize=100
      - --accessLog.filters.statusCodes=200-299,400-499,500-599
      - --providers.docker=true
      - --providers.docker.endpoint=tcp://socket-proxy:2375
      - --providers.docker.exposedByDefault=false
      - --providers.docker.network=t3_proxy
      - --providers.file.directory=/rules
      - --providers.file.watch=true
    volumes:
      - $DOCKERDIR/appdata/traefik/rules:/rules
      - $DOCKERDIR/logs/traefik:/logs
    environment:
      - TZ=$TZ
      - DOMAINNAME
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik-rtr.entrypoints=websecure
      - traefik.http.routers.traefik-rtr.rule=Host(`traefik.$DOMAINNAME`)
      - traefik.http.routers.traefik-rtr.service=api@internal
      - traefik.http.routers.traefik-rtr.middlewares=chain-authentik@file
      - homepage.group=Management
      - homepage.name=Traefik
      - homepage.icon=traefik.png
      - homepage.href=https://traefik.$DOMAINNAME
      # Widget disabled until homepage can bypass auth for traefik api
      # - homepage.widget.type=traefik
      # - homepage.widget.url=https://traefik.$DOMAINNAME

