services:
  xmltv:
    image: ghcr.io/cl-ansy/xmltv-gateway:latest
    container_name: xmltv
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    environment:
      PROVIDER: hdhomerun
      HDHOMERUN_HOST: $TV_TUNER_HOST
    restart: unless-stopped
