---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

# - My First Group:
#     - My First Service:
#         href: http://localhost/
#         description: Homepage is awesome

