---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

title: Numenor
headerStyle: boxed
statusStyle: dot

layout:
  Infrastructure:
    style: row
    columns: 4
  Media:
    style: row
    columns: 2
  PVR:
    style: row
    columns: 2
  Downloads:
    style: row
    columns: 2
  Monitoring:
    style: row
    columns: 2
  Management:
    style: row
    columns: 2

logpath: /app
